---
# tasks file for django_role
- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:  
    - python3-dev
    - python3-virtualenv
    - python3-pip
    - virtualenv

- name: Create directory_project
  ansible.builtin.file:
    path: "{{ project_name_path }}"
    state: directory

- name: Install Django framework
  ansible.builtin.pip:
    requirements: "/home/vagrant/test_project/requirements.txt"
    virtualenv: "{{ project_name_path }}/venv"

- name: Install a django project
  ansible.builtin.command: "{{ project_name_path }}/venv/bin/django-admin.py startproject {{ project_name }} chdir={{ project_name_path }}/"

- name: Create Settings File for Django
  ansible.builtin.template:
    src: settings.py.j2
    dest: "{{ project_name_path }}/{{ project_name }}/{{ project_name }}/settings.py"

- name: Make migrations
  ansible.builtin.shell: "{{project_name_path}}/venv/bin/python3 {{ project_name_path }}/{{ project_name }}/manage.py makemigrations"

- name: Migrate database
  community.general.django_manage: 
    project_path: "{{ project_name_path }}/{{ project_name }}"
    command: migrate
    virtualenv: "{{project_name_path}}/venv"
